---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acrscanner
rules:
- apiGroups: [""]
  resources: ["pods", "replicationcontrollers"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acrscanner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acrscanner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acrscanner
subjects:
  - kind: ServiceAccount
    name: acrscanner
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acr-kube-image-scan
  labels:
    app: image-scan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-scan
  template:
    metadata:
      labels:
        app: image-scan
    spec:
      containers:
      - name: image-scanner
        image: <registry-name>.azurecr.io/acr-kube-image-scan:latest
        env:
        - name: SCANNER_LOG_LEVEL
          value: "DEBUG"
        - name: SYNC_IN_MINUTES
          value: "24h"        
        volumeMounts:
        - name: config
          mountPath: "/config/imagescan"
          readOnly: true
      serviceAccountName: acrscanner
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: config
        secret:
          secretName: acr-kube-image-scan-config
      nodeSelector: 
        "beta.kubernetes.io/os": linux